// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIOwzE0B0AARdmFqh2zG_aUVBsCy8zRLo',
    appId: '1:973274459746:web:0e18e0bb81ede4e46eab3b',
    messagingSenderId: '973274459746',
    projectId: 'ija-chat-3ed15',
    authDomain: 'ija-chat-3ed15.firebaseapp.com',
    storageBucket: 'ija-chat-3ed15.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYv_ojS_Nym-n8ZsnoGBoWF8eqspyOSWc',
    appId: '1:973274459746:android:857a6151362b453d6eab3b',
    messagingSenderId: '973274459746',
    projectId: 'ija-chat-3ed15',
    storageBucket: 'ija-chat-3ed15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh2696sXBgZD9LcDR3qToOFi40-cIiS0I',
    appId: '1:973274459746:ios:af3235a4f989c67e6eab3b',
    messagingSenderId: '973274459746',
    projectId: 'ija-chat-3ed15',
    storageBucket: 'ija-chat-3ed15.firebasestorage.app',
    iosBundleId: 'com.example.ijaChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh2696sXBgZD9LcDR3qToOFi40-cIiS0I',
    appId: '1:973274459746:ios:af3235a4f989c67e6eab3b',
    messagingSenderId: '973274459746',
    projectId: 'ija-chat-3ed15',
    storageBucket: 'ija-chat-3ed15.firebasestorage.app',
    iosBundleId: 'com.example.ijaChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIOwzE0B0AARdmFqh2zG_aUVBsCy8zRLo',
    appId: '1:973274459746:web:7d9a1f7a032571226eab3b',
    messagingSenderId: '973274459746',
    projectId: 'ija-chat-3ed15',
    authDomain: 'ija-chat-3ed15.firebaseapp.com',
    storageBucket: 'ija-chat-3ed15.firebasestorage.app',
  );
}
